apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      postgresVersion: 1600
      sslmode: "disable"
      timescaledb: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    url: db:5432
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
